[workspace]
resolver = "2"
members = ["l10n-lib", "l10n-bin"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
l10n = { git = "https://github.com/MathieuTricoire/l10n" }
